### PR TITLE
Clever cloud deployment config

### PR DESCRIPTION
**Pull request by zorglube**
This PR depend on the evolution of : https://github.com/zorchenhimer/MovieNight/pull/197

### CODE REVIEW

**Review by CptPie — COMMENTED** [review]
Is `MN_BUID_CONFIG` a typo?

**Comment by zorglube** [comment]
> Is `MN_BUID_CONFIG` a typo?

I'd love to !

**Comment by zorglube** [comment]
@zorchenhimer : I'm not resigning on this, I'm just missing time nowadays.

**Comment by zorglube** [comment]
Few hours of work and it will be good.

**Comment by zorglube** [comment]
@CptPie : Ready for review \o/

**Pull request merged**
