### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by zorglube**
TrueNAS plugin is released.

### CODE REVIEW

**Comment by zorchenhimer** [comment]
You're gonna have to rebase this.  I'm not merging 31 commits to only have a few lines in the readme change.  If that doesn't clean it up, cherry pick the changes into a new branch and make a PR on that.

**Comment by zorglube** [comment]
Definitely your right. 
I'll make things cleaner.

**Comment by zorglube** [comment]
Damn I fucked-up my squash...

**Comment by zorglube** [comment]
@zorchenhimer If I didn't made any mistake, it's good to be merge now. 

You tell me ;-)

**Pull request closed without merging**
